apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
        - name: aggregator-service
          image: ranaliw/aggregator-service:latest
          ports:
            - containerPort: 6000
          envFrom:
            - secretRef:
                name: healthsync-db-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  selector:
    app: aggregator-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: LoadBalancer
